#!/bin/bash

#rippledcnflc1=`/bin/cat /keystore/rippled1.cfg 2>/dev/null | wc -l`
#rippledcnflc2=`/bin/cat /keystore/rippled2.cfg 2>/dev/null | wc -l`
#rippledcnflc3=`/bin/cat /keystore/rippled3.cfg 2>/dev/null | wc -l`
#ripplevalidatorkslc=`/bin/cat /keystore/validator-keys.json 2>/dev/null | wc -l`
#validatorslc=`/bin/cat /keystore/validators.txt 2>/dev/null | wc -l`

#mkdir -p /root/.ripple
#mkdir -p /keystore

#if [[ "$rippledcnflc" -gt "0" && "$ripplevalidatorkslc" -gt "0" && "$validatorslc" -gt "0" ]]; then
#if [[ "$rippledcnflc1" -gt "0" && "$rippledcnflc2" -gt "0" && "$validatorslc" -gt "0" && "$rippledcnflc3" -gt "0" ]]; then

#    echo "Existing rippled config at host /keystore/, using them."

#    rm /etc/opt/ripple/rippled.cfg
#    rm /etc/opt/ripple/validators.txt
#    /bin/cat /keystore/rippled1.cfg > /etc/opt/ripple/rippled1.cfg
#    /bin/cat /keystore/rippled2.cfg > /etc/opt/ripple/rippled2.cfg
#    /bin/cat /keystore/rippled3.cfg > /etc/opt/ripple/rippled3.cfg
#    /bin/cat /keystore/validators.txt > /etc/opt/ripple/validators.txt
#    /bin/cat /keystore/validator-keys.json > /root/.ripple/validator-keys.json

#fi

#if [[ "$ripplevalidatorkslc" -lt "1" ]]; then
#
#    echo "No host-validator-keys, generating validator keys"
#
#    /opt/ripple/bin/validator-keys create_keys
#    /bin/cat /root/.ripple/validator-keys.json > /keystore/validator-keys.json 2>/dev/null
#
#    token=$(/opt/ripple/bin/validator-keys create_token --keyfile /root/.ripple/validator-keys.json)
#    token=${token#*]}
#
#    cp /etc/opt/ripple/rippled.cfg /rippled.cfg
#    echo "[validator_token]" >> /rippled.cfg
#    echo $token | tr " " "\n" >> /rippled.cfg
#    cp /rippled.cfg /etc/opt/ripple/rippled.cfg
#    rm /rippled.cfg
#
#    /bin/cat /etc/opt/ripple/rippled.cfg > /keystore/rippled.cfg 2>/dev/null
#    /bin/cat /etc/opt/ripple/validators.txt > /keystore/validators.txt 2>/dev/null
#
#fi

# Start rippled, Passthrough other arguments
/root/.nvm/versions/node/v14.17.3/bin/node /sntrippled/grpc/one4all.js
exec /opt/ripple/bin/rippled --conf /opt/ripple/etc/rippled3.cfg --quorum 3 "$@"
##exec /root/.nvm/versions/node/v14.17.3/bin/node /sntrippled/grpc/one4all.js
##exec node /hello.js
#exec bash